server:
  port: ${PORT:8080}

spring:
  cloud:
    stream:
      defaultBinder: myKafkaBinder
      binders:
        myKafkaBinder:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
      bindings:
        requests_output:
          destination: requests
#          producer:
#            partitionKeyExtractorName: customPartitionKeyExtractor
        requests_input:
          destination: requests
          group: my-requests-group
          consumer.partitioned: true
        replies_input:
          destination: replies
        replies_output:
          destination: replies